algoritmo "Escola"
var
Pnota, Snota, Media: Real
inicio
EscrevaL("----------------------")
EscrevaL("ESCOLA JAVALI CANSADO")
EscrevaL("----------------------")
Escreva("Primeira Nota: ")
Leia(Pnota)
EScreva("Segunda Nota: ")
Leia(Snota)
EscrevaL("----------------------")
Media <- (Pnota + Snota) / 2)
EscrevaL("MEDIA: ", Media:3:1)
Se ( Media >= 7 )entao
   EscrevaL(" ALUNO APROVADO ")
Senao
   EscrevaL(" ALUNO REPROVADO ")
   EscrevaL("----------------------")
FimSe
fimalgoritmo
